### PR TITLE
[FEATURE] Add ProcessCommand

### PR DESCRIPTION
**Pull request by dhuf**

### CODE REVIEW

**Comment by thommyhh** [comment]
@dhuf Thanks for the contribution. Would you allow me to push to this branch? I've a few changes I'd like to make before merging it.

**Comment by dhuf** [comment]
@thommyhh of course, with pleasur. Thanks

**Comment by dhuf** [comment]
Just added a missed upstream bugfix

**Comment by thommyhh** [comment]
@dhuf I still couldn't push. As far as I read, it is only possible on user-owned forks. I create another PR and incorporated my changes. Thanks again for your contribution.

**Pull request closed without merging**
